In [1]:
import pandas as pd

In [2]:
df1 = pd.read_table('HT_Sensor_dataset.dat')

In [3]:
df1.head()

id time  \
0  0  -0.999750  12.862100  10.368300  10.438300 ...   
1  0  -0.999472  12.861700  10.368200  10.437500 ...   
2  0  -0.999194  12.860700  10.368600  10.437000 ...   
3  0  -0.998916  12.860200  10.368600  10.437000 ...   
4  0  -0.998627  12.859500  10.368800  10.437400 ...   

         R1         R2         R3         R4         R5         R6         R7        R8        Temp.      Humidity  
0                                                NaN                                                                
1                                                NaN                                                                
2                                                NaN                                                                
3                                                NaN                                                                
4                                                NaN

In [4]:
df1['id time']

0         0  -0.999750  12.862100  10.368300  10.438300 ...
1         0  -0.999472  12.861700  10.368200  10.437500 ...
2         0  -0.999194  12.860700  10.368600  10.437000 ...
3         0  -0.998916  12.860200  10.368600  10.437000 ...
4         0  -0.998627  12.859500  10.368800  10.437400 ...
                                ...                        
928986    99  1.675182  12.622400  10.580500  10.743200 ...
928987    99  1.675460  12.623600  10.579600  10.743600 ...
928988    99  1.675738  12.624400  10.579500  10.743700 ...
928989    99  1.676016  12.624300  10.579700  10.744000 ...
928990    99  1.676304  12.624800  10.579100  10.744000 ...
Name: id time, Length: 928991, dtype: object

In [5]:
x = []
for i in df1['id time']:
    x.append(i.split())

In [6]:
df2 = pd.DataFrame(x,columns=['id','time', 'R1' ,'R2','R3','R4','R5','R6','R7','R8','Temp' ,'Humidity'])

In [7]:
df2.head()

id       time         R1         R2         R3         R4         R5  \
0  0  -0.999750  12.862100  10.368300  10.438300  11.669900  13.493100   
1  0  -0.999472  12.861700  10.368200  10.437500  11.669700  13.492700   
2  0  -0.999194  12.860700  10.368600  10.437000  11.669600  13.492400   
3  0  -0.998916  12.860200  10.368600  10.437000  11.669700  13.492100   
4  0  -0.998627  12.859500  10.368800  10.437400  11.669900  13.491900   

          R6        R7        R8       Temp   Humidity  
0  13.342300  8.041690  8.739010  26.225700  59.052800  
1  13.341200  8.041330  8.739080  26.230800  59.029900  
2  13.340500  8.041010  8.739150  26.236500  59.009300  
3  13.339800  8.040860  8.739360  26.241600  58.990500  
4  13.339000  8.040870  8.739860  26.246200  58.973600

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928991 entries, 0 to 928990
Data columns (total 12 columns):
id          928991 non-null object
time        928991 non-null object
R1          928991 non-null object
R2          928991 non-null object
R3          928991 non-null object
R4          928991 non-null object
R5          928991 non-null object
R6          928991 non-null object
R7          928991 non-null object
R8          928991 non-null object
Temp        928991 non-null object
Humidity    928991 non-null object
dtypes: object(12)
memory usage: 85.1+ MB


In [9]:
df2['id'] = df2['id'].astype(int)
df2['time'] = df2['time'].astype(float)
df2['R1'] = df2['R1'].astype(float)
df2['R2'] = df2['R2'].astype(float)
df2['R3'] = df2['R3'].astype(float)
df2['R4'] = df2['R4'].astype(float)
df2['R5'] = df2['R5'].astype(float)
df2['R6'] = df2['R6'].astype(float)
df2['R7'] = df2['R7'].astype(float)
df2['R8'] = df2['R8'].astype(float)
df2['Temp'] = df2['Temp'].astype(float)
df2['Humidity'] = df2['Humidity'].astype(float)

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928991 entries, 0 to 928990
Data columns (total 12 columns):
id          928991 non-null int64
time        928991 non-null float64
R1          928991 non-null float64
R2          928991 non-null float64
R3          928991 non-null float64
R4          928991 non-null float64
R5          928991 non-null float64
R6          928991 non-null float64
R7          928991 non-null float64
R8          928991 non-null float64
Temp        928991 non-null float64
Humidity    928991 non-null float64
dtypes: float64(11), int64(1)
memory usage: 85.1 MB


In [11]:
from tsfresh.feature_extraction import extract_features
from tsfresh.feature_extraction import settings

import numpy as np
import pandas as pd

In [12]:
settings.ComprehensiveFCParameters, settings.EfficientFCParameters, settings.MinimalFCParameters

(tsfresh.feature_extraction.settings.ComprehensiveFCParameters,
 tsfresh.feature_extraction.settings.EfficientFCParameters,
 tsfresh.feature_extraction.settings.MinimalFCParameters)

In [13]:
settings_minimal = settings.MinimalFCParameters() 
settings_minimal

{'sum_values': None,
 'median': None,
 'mean': None,
 'length': None,
 'standard_deviation': None,
 'variance': None,
 'maximum': None,
 'minimum': None}

In [14]:
X_tsfresh = extract_features(df2, column_id="id", default_fc_parameters=settings_minimal)
X_tsfresh.head()

Feature Extraction: 100%|██████████| 30/30 [00:00<00:00, 77.67it/s]


variable  Humidity__length  Humidity__maximum  Humidity__mean  \
id                                                              
0                  12815.0            60.7326       58.094139   
1                   8914.0            60.5740       57.075808   
2                   9498.0            57.5553       55.958283   
3                   9309.0            73.9476       60.235128   
4                   5396.0            56.2517       54.528536   

variable  Humidity__median  Humidity__minimum  Humidity__standard_deviation  \
id                                                                            
0                 58.00730            56.0856                      1.158678   
1                 56.91445            55.2840                      1.035244   
2                 55.87525            54.3326                      0.611602   
3                 57.24200            55.3568                      5.954285   
4                 54.36145            53.0745                      0.680697   

variable  Humidity__sum_values  Humidity__variance  R1__length  R1__maximum  \
id                                                                            
0                  744476.3947            1.342535     12815.0      13.2902   
1                  508773.7516            1.071731      8914.0      13.3792   
2                  531491.7744            0.374057      9498.0      13.2724   
3                  560728.8051           35.453514      9309.0      13.4216   
4                  294235.9818            0.463348      5396.0      12.4383   

variable  ...  Temp__sum_values  Temp__variance  time__length  time__maximum  \
id        ...                                                                  
0         ...       339485.5149        0.074891       12815.0       2.634728   
1         ...       228908.7750        0.031862        8914.0       1.534930   
2         ...       247526.2598        0.012317        9498.0       1.659864   
3         ...       238315.2731        0.166058        9309.0       1.719998   
4         ...       141773.2507        0.035658        5396.0       1.529729   

variable  time__mean  time__median  time__minimum  time__standard_deviation  \
id                                                                            
0           0.836301      0.837083      -0.999750                  1.038550   
1           0.250600      0.248874      -0.999798                  0.724202   
2           0.330105      0.330208      -0.999890                  0.768101   
3           0.335799      0.341032      -0.999881                  0.784538   
4           0.767090      0.774904      -0.020839                  0.446518   

variable  time__sum_values  time__variance  
id                                          
0             10717.195523        1.078586  
1              2233.847747        0.524469  
2              3135.339255        0.589979  
3              3125.952756        0.615500  
4              4139.218981        0.199378  

[5 rows x 88 columns]

In [15]:
Meta_data = pd.read_table("HT_Sensor_metadata.dat")

In [16]:
Meta_data.head()

id      date Unnamed: 2  class    t0  dt
0   0  07-04-15     banana  13.49  1.64 NaN
1   1  07-05-15       wine  19.61  0.54 NaN
2   2  07-06-15       wine  19.99  0.66 NaN
3   3  07-09-15     banana   6.49  0.72 NaN
4   4  07-09-15       wine  20.07  0.53 NaN

In [17]:
Meta_data.columns 

Index(['id', 'date', 'Unnamed: 2', 'class', 't0', 'dt'], dtype='object')

In [18]:
categories = []
for filename in Meta_data["Unnamed: 2"]:
    if filename == 'banana':
        categories.append(1)
    elif filename == 'wine':
         categories.append(2)
        
    else:
        categories.append(0)


In [19]:
categories = pd.DataFrame(categories)
categories.columns = ["Target"]

In [20]:
Meta_data = Meta_data.drop(["id","date","dt","Unnamed: 2"],axis=1)

In [21]:
data = pd.concat([X_tsfresh,Meta_data,categories],axis=1)

In [22]:
data.head()

Humidity__length  Humidity__maximum  Humidity__mean  Humidity__median  \
0           12815.0            60.7326       58.094139          58.00730   
1            8914.0            60.5740       57.075808          56.91445   
2            9498.0            57.5553       55.958283          55.87525   
3            9309.0            73.9476       60.235128          57.24200   
4            5396.0            56.2517       54.528536          54.36145   

   Humidity__minimum  Humidity__standard_deviation  Humidity__sum_values  \
0            56.0856                      1.158678           744476.3947   
1            55.2840                      1.035244           508773.7516   
2            54.3326                      0.611602           531491.7744   
3            55.3568                      5.954285           560728.8051   
4            53.0745                      0.680697           294235.9818   

   Humidity__variance  R1__length  R1__maximum  ...  time__maximum  \
0            1.342535     12815.0      13.2902  ...       2.634728   
1            1.071731      8914.0      13.3792  ...       1.534930   
2            0.374057      9498.0      13.2724  ...       1.659864   
3           35.453514      9309.0      13.4216  ...       1.719998   
4            0.463348      5396.0      12.4383  ...       1.529729   

   time__mean  time__median  time__minimum  time__standard_deviation  \
0    0.836301      0.837083      -0.999750                  1.038550   
1    0.250600      0.248874      -0.999798                  0.724202   
2    0.330105      0.330208      -0.999890                  0.768101   
3    0.335799      0.341032      -0.999881                  0.784538   
4    0.767090      0.774904      -0.020839                  0.446518   

   time__sum_values  time__variance  class    t0  Target  
0      10717.195523        1.078586  13.49  1.64       1  
1       2233.847747        0.524469  19.61  0.54       2  
2       3135.339255        0.589979  19.99  0.66       2  
3       3125.952756        0.615500   6.49  0.72       1  
4       4139.218981        0.199378  20.07  0.53       2  

[5 rows x 91 columns]

In [23]:
data = data.dropna()

In [24]:
from pycaret.classification import *
clf1 = setup(data = data, target = 'Target')
# comparing all models
compare_models()

In [25]:
from sklearn.model_selection import train_test_split
X = data.drop('Target',1)
y = data.Target


In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=30)

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [28]:
classifier = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [29]:
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [30]:
y_pred = classifier.predict(X_test)

In [31]:
print(accuracy_score(y_test,y_pred))

0.9090909090909091


In [32]:
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 1  5  2]
 [ 0  0 11]]


In [33]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.62      0.77         8
           2       0.85      1.00      0.92        11

    accuracy                           0.91        33
   macro avg       0.93      0.88      0.88        33
weighted avg       0.92      0.91      0.90        33

